### ISSUE TITLE
Persian Date Field in backend 

### ISSUE THREAD

**Issue by ajmanco** [octoberfa/oc-persian#13]
Hi
I'v extend Users plugin in backend . but in date fields dates shows as a Gregorian dates . it dont converd dates to persian date . we save dates in database as a Gregorian date . but i want to convert it to persian date in view . Do you have a solution for this ?

tnx

**Comment by shayanline** [comment]
@ajmanco Hi Ajmanco, for this purpose you need to change the backend language to Farsi.

**Comment by TheServat** [comment]
fixed in next release.
