### ISSUE TITLE
Outdated Verta dependency.

### ISSUE THREAD

**Issue by shayanline** [octoberfa/oc-persian#15]
Verta package is outdated and caused error in the latest version of OctoberCMS installed (469).

Managed to fix the error by manually updating Verta package to the latest version (1.10.7) from the author's repo:

[Verta Github Repo](https://github.com/hekmatinasser/verta)

It's really nice of you if you update the Verta installation in this repo as well.

**Comment by TheServat** [comment]
Verta will removed from this plugin in next release
